// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNBf8vGNWkvMH0tV9OcAtmXrXQc71bc2M',
    appId: '1:136355341868:web:49a8a07e35a48abf37d389',
    messagingSenderId: '136355341868',
    projectId: 'car-rental-app-167e8',
    authDomain: 'car-rental-app-167e8.firebaseapp.com',
    storageBucket: 'car-rental-app-167e8.firebasestorage.app',
    measurementId: 'G-ZW65ZC4HGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJklKOApY7JJQqtd6HBszVaG3qSFFRSkU',
    appId: '1:136355341868:android:a42c27142aab589137d389',
    messagingSenderId: '136355341868',
    projectId: 'car-rental-app-167e8',
    storageBucket: 'car-rental-app-167e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG1tGF0xbNeiSOgd43VZLYD-Kdl0yNN3E',
    appId: '1:136355341868:ios:952a8d87d6e12bed37d389',
    messagingSenderId: '136355341868',
    projectId: 'car-rental-app-167e8',
    storageBucket: 'car-rental-app-167e8.firebasestorage.app',
    iosBundleId: 'com.example.carRentalAppFirebase',
  );
}
